version: "3.3"
services:
  test_app:
    image: docker-nextjs
    ports:
      - 3000:3000
    build: .
    volumes:
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles
      - ./components:/app/components
      - ./utils:/app/utils
      - ./models:/app/models
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./database-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_USERPASS}
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin123
      - ME_CONFIG_MONGODB_SERVER=mongodb
