import Head from "next/head";
import AppLayout from "../components/AppLayout";
import Button from "../components/Button";
import GitHub from "../components/icons/GitHub";
import { colors } from "../styles/theme";

export const Home = () => {
  return (
    <>
      <Head>
        <title>Devter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout>
        <section>
          <img src="/logo-devter.png" alt="devter" />
          <h1>Devter</h1>
          <h2>
            Habla sobre desarrolo <br /> con programadores
          </h2>
          <div>
            <Button>
              <GitHub width={24} height={24} />
              Login with GitHub
            </Button>
          </div>
        </section>
      </AppLayout>
      <style jsx>{`
        div {
          margin-top: 16px;
        }
        img {
          width: 120px;
        }
        h1 {
          color: ${colors.primary};
          font-weight: 800;
          margin-bottom: 0;
          font-size: 21px;
        }
        h2 {
          color: ${colors.secondary};
          font-size: 18px;
        }
        section {
          display: grid;
          height: 100%;
          place-content: center;
          place-items: center;
        }
      `}</style>
    </>
  );
};

export default Home;
