import Head from "next/head";
import AppLayout from "../components/appLayout";

export const Home = () => {
  return (
    <div>
      <Head>
        <title>Devter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout>
        <img src="#" alt="devter" />
        <h1>Devter</h1>
        <h2>Habla sobre desarrolo con programadores:</h2>
      </AppLayout>
    </div>
  );
};

export default Home;
