import Head from "next/head";
export default function AppLayout({ children }) {
  return (
    <>
      <Head>
        <title>Devter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full h-[100vh]">{children}</main>
    </>
  );
}
